### ISSUE TITLE
Code deploy features in CFT

### ISSUE THREAD

**Issue by DevOpsAirflow** [villasv/turbine#120]
We are planing to deploy our DAGS using jenkins. In this case do we need code deploy? if we remove code deploy piece from CFT will it impact any airflow functionality?

**Comment by villasv** [comment]
Nope ;-) No problem, but you'll have to handle your deployments with new instances from AutoScaling. If you disable auto scaling, everything should be fine.

**Comment by parthu50** [comment]
Thanks. Also, i guess not sure whether its related or not but we see /tmp/env.sh got deleted and some code references in /tmp. any idea why its happening ?

**Comment by villasv** [comment]
Did the instance restart? If so, it may explain the `/tmp` directory being wiped out. But the CFN initialization script will always recreate the `env.sh` file before running stuff that depends on it.
