### ISSUE TITLE
Store the Fernet key inside AWS Systems Manager Parameter Store

### ISSUE THREAD

**Issue by villasv** [villasv/turbine#123]
Issue #107 is concerned with key generation, but even if it's criptographically secure to generate it the current way, it's stored in EFS. I need to investigate further if this is secure.

**Comment by waterytowers** [comment]
We store our fernet key in parameter store encrypted using kms.  It is retrieved at startup time.  The iam role attached to the airflow instance is provided exclusive access to decrypt with the kms key and read access to the path.  It worked well for us.

Not sure if this is something you might want to implement?  It is only a suggestion.

We were using airflow for a while but moved over to using aws step functions for orchestration.  We had too many issues with jobs failing and not being cleaned up and if there were code issues in the python jobs it would create issues with the UI.  Last major annoyance was if you left airflow to have too much history the UI would slow down a eventually become unusable.  We stopped using it about 12 months ago so maybe things have improved?

**Comment by villasv** [comment]
Thanks for the inputs, @waterytowers ! I'll take a look at KMS, it seems like it's the perfect fit.

I still haven't reached a scale that Airflow wasn't able to handle, so I can't say much if the scenarios you described are any better in the latest release.

**Comment by villasv** [comment]
Finished in 1bc20484736467bc217c757b01bd287bf563b172
