### ISSUE TITLE
Question about Cloud formation Template Parameter Value

### ISSUE THREAD

**Issue by ashishusoni** [villasv/turbine#133]
If my VPC Cidr block is 10.248.80.0/22 then what should be the correct values of stack and dummy subnet ?

**Comment by villasv** [comment]
It depends mostly on the other existing subnets, but something like 10.248.80.0/24 and 10.248.81.0/24.

Any CIDR partitioning strategy would work, so if you have any doubts you can look for guides on subnet partitioning.
