### ISSUE TITLE
Access to bucket with templates.

### ISSUE THREAD

**Issue by IgorGerasimov** [villasv/turbine#135]
Seems like access to `https://turbine-quickstart.s3.amazonaws.com/quickstart-turbine-airflow/templates/turbine-master.template` is forbidden.

[https://prnt.sc/pwzax2](url)

**Comment by villasv** [comment]
Ooops. This looks like a deployment problem.

**Comment by villasv** [comment]
Should be working now. Thanks for the heads up!
