### ISSUE TITLE
Files not syncing in S3 with master branch

### ISSUE THREAD

**Issue by Msquared63** [villasv/turbine#146]
It almost done when I got the error:

The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4ed17e65-d615-4e0f-b8e6-2bba91d30e2d)

**Comment by Msquared63** [comment]
Hi,

This template is out of date: https://turbine-quickstart.s3.amazonaws.com/quickstart-turbine-airflowtemplates/turbine-workerset.template

Thanks.

Mike

**Comment by Msquared63** [comment]
Downloaded the latest to my own bucket.  Had to zip load_metric.py but it worked.

**Comment by villasv** [comment]
Oops, I think the CI has been failing silently to upload the files to S3 after I changed to GitHub actions. Thanks for the report, I'll give it a look!
