### ISSUE TITLE
Werkzeug dependency causing new Turbine deployments to fail installation

### ISSUE THREAD

**Issue by izzoa** [villasv/turbine#151]
There's an issue with the Werkzeug dependency that is causing airflow to crash on startup for new Turbine deployments, see here:
#https://github.com/apache/airflow/pull/7377

Recommend updating the stack to use Airflow >= 1.10.9.

**Comment by izzoa** [comment]
#152 Pull request submitted

**Comment by villasv** [comment]
Oh, thanks for pointing it out :-)
