### ISSUE TITLE
Dependency issue with openssl

### ISSUE THREAD

**Issue by RafaelAMello** [villasv/turbine#164]
There seems to be an issue that breaks the deployment of Airflow.
Debugging it looks changing:

https://github.com/villasv/aws-airflow-stack/blob/37233f0d872e54f0e44e855d006ce15ea08ce0ac/templates/turbine-cluster.template#L501-L506

To this:

```bash
                PYCURL_SSL_LIBRARY=openssl pip3 install \
                  --no-cache-dir --compile --ignore-installed \
                  pycurl
                PYCURL_SSL_LIBRARY=openssl SLUGIFY_USES_TEXT_UNIDECODE=yes pip3 install \
                  celery[sqs] \
                  apache-airflow[celery,postgres,s3,crypto]==1.10.9
```

FIxes the issue

**Comment by villasv** [comment]
Thanks @RafaelAMello, you're absolutely right.

The `PYCURL_SSL_LIBRARY`  in the previous line stopped working after the upgrade to airflow 1.10.9, your change fixes the issue indeed. I've got this change on the `develop` branch and should see that in a new release by April.
