### ISSUE TITLE
Deployment failts outside us-east-1 using hosted template

### ISSUE THREAD

**Issue by villasv** [villasv/turbine#174]
Lambda packages must be in a bucket in the same region as the deployment occurs, so to really support more regions, the templates must be published on one bucket for each region.

**Comment by ilyanoskov** [comment]
@villasv I am still experiencing this issue.

**Comment by ilyanoskov** [comment]
https://github.com/villasv/aws-airflow-stack/issues/180

**Comment by villasv** [comment]
This is not the same issue, as for this one the deployment failed on CloudFormation but on the reference issue it does not.
