### ISSUE TITLE
EFS not being mounted to wokers

### ISSUE THREAD

**Issue by RohitJones** [villasv/turbine#187]
Hi, Villasv

Thank you for all your hard work !
There is a minor bug in the workerset.setup.sh script, [specifically in the if condition](https://github.com/villasv/aws-airflow-stack/blob/master/scripts/workerset.setup.sh#L5). 
The condition should be `if [ ! -d "/mnt/efs" ]` so that it evaluates to true when the efs directory does not exist.

**Comment by villasv** [comment]
Wow, what a slip! Thanks for pointing it out and for the quickfix :-)
