### ISSUE TITLE
Celery with SQS

### ISSUE THREAD

**Issue by shashankn91** [villasv/turbine#43]
I was reading a blog post about SQS that was not working well with Airflow .

https://medium.com/@Twistacz/whats-wrong-with-sqs-and-why-we-gave-it-up-22780d4f48ef

Is this the case now ??? 
If so what is the best broker to make it work in AWS environment .

**Comment by villasv** [comment]
I didn't observe any issues with SQS as a backend. There are observability downsides and upsides. There's no way to use Celery Flower, for example, but CloudWatch alarms are very versatile.

**Comment by shashankn91** [comment]
This is not related to celery !!! There is 1 issue I face regularly when I setup python environment . In requirements.txt if I have the version airflow 1.9.0 next time in y deployment if I increment my version to 1.10.0 then according to the script it directly installs 1.10.0 which causes issues because dependencies of 1.10.0 will be different . I way I thought it can be handles was have a Virtual env which installs and remove the env every time it is deployed and recreate the env and run it in the new env . Let me know if I am thinking in the right direction.

**Comment by villasv** [comment]
> 
> 
> This is not related to celery !!! There is 1 issue I face regularly when I setup python environment . In requirements.txt if I have the version airflow 1.9.0 next time in y deployment if I increment my version to 1.10.0 then according to the script it directly installs 1.10.0 which causes issues because dependencies of 1.10.0 will be different . I way I thought it can be handles was have a Virtual env which installs and remove the env every time it is deployed and recreate the env and run it in the new env . Let me know if I am thinking in the right direction.

The blog post you mentioned is about Celery, not Airflow. Are you reporting another issue?
