### ISSUE TITLE
Guess the AMI identifier from the region and an internal map

### ISSUE THREAD

**Issue by villasv** [villasv/turbine#55]
That's usually how it's done in CFN templates that allow multiple regions. Is there a plausible reason to pick one AMI over another inside a region? Which type to pick as default?

**Comment by tomfaulhaber** [comment]
I didn't do this since we have to keep the template up to date when new AMIs are released. (I wish cloud formation had a way to just pick the latest Amazon Linux AMI.)

That said, I'm pretty easy. If you think it's a good idea, I'm happy with that. It's definitely easier for the users.

**Comment by villasv** [comment]
I'll do it with the new AMIs after #53

**Comment by villasv** [comment]
Useful snippet:

```
$ regions=$(aws ec2 describe-regions --query "Regions[].RegionName" --output text)
$ for region in $regions; do ami=$(aws --region $region ec2 describe-images --filters "Name=name,Values=amzn2-ami-hvm-2.0.20180622.1-x86_64-gp2" --query "Images[0].ImageId" --output "text"); printf "'$region':\n  AMI: '$ami'\n"; done
```
