### ISSUE TITLE
Install python dependencies on all nodes

### ISSUE THREAD

**Issue by rddefauw** [villasv/turbine#66]
I wanted to try the new AWS SageMaker operators.  Installing the sagemaker python module pulls in dependencies like scipy with static libraries, and those cannot be packaged into a zip file with the DAG.  The CFN template should let you provide a list of python modules that are installed on all nodes, including the interface node and the worker nodes, during initialization.

**Comment by villasv** [comment]
True, we can't assume that users will not require more Airflow dependencies.

The stack used to have an init script that installed dependences from a standard `requirements.txt` file location (inside `AIRFLOW_HOME`). It was removed during the `sysvinit` to `systemd` migration, which is kind of a regression.

I think I'll use this issue to reintroduce that feature, sounds good?

The plan is to adopt CodeDeploy later on and this would behave differently, but I guess this is too important to wait.

**Comment by rddefauw** [comment]
Sounds great.  The workaround for now is to manually install the dependencies on each node, but of course it's tricky with autoscaling.

**Comment by villasv** [comment]
Done in 26c72f8. You still have to manually install in the scheduler and webserver, but worker nodes will automatically install from `/efs/airflow/requirements.txt`
