### ISSUE TITLE
Specify an IAM role for the EC2 instances

### ISSUE THREAD

**Issue by rddefauw** [villasv/turbine#69]
In order to use the new Sagemaker operators, the instances need a role that gives them permission to invoke the Sagemaker operations through boto3.

**Comment by villasv** [comment]
This is going to be tricky. That's definitely important, though it would be best if the stack was as much as self-contained as possible.

If we ask for an external IAM Role, it has to be optional (optional stuff are hard in CF). If it's internal, it would probably have lots of parametrization and difficult defaults as well.

Will look into it.

**Comment by villasv** [comment]
Closed in c658a27. It still not enough to use Sagemaker, I'm just using the IAM Role internally, but soon enough I'll add a parameter specifying Sagemaker permissions.
