### ISSUE TITLE
Sagemaker operators do not pick up correct region

### ISSUE THREAD

**Issue by rddefauw** [villasv/turbine#70]
The new Sagemaker operators by default use the us-east-1 endpoint via boto3.  In order to get around that I had to alter the default aws hook configuration in the Airflow database:

  update connection set extra = '{"region_name": "us-west-2"}' where conn_id = 'aws_default';

The CFN template should configure the database with the correct AWS region, in addition to writing out the environment variables.

**Comment by villasv** [comment]
Hmm, I'm usure about this one. Configuring Airflow connections may be going too deep.

IMO it's a bit invasive for the stack to fiddle with the default Airflow connections. It's reasonably expected that you need to configure your connections before using them, and adjusting the region is just a part of that. It's possible that it could break someone's code because they deploy their stack on `us-east-2` but relies on that default to communicate with `us-east-1`.

I'll ask around for more opinions.

**Comment by villasv** [comment]
Just a reminder that you can also change that `aws_default` connection region using the CLI and the UI, which is why it's considered a reasonable thing to ask for the users.

I guess we could argue that Airflow should drop that region default and let boto3 handle things.

**Comment by rddefauw** [comment]
Perhaps start with a documentation update?  I assumed that since the CFN template was setting the region in the environment, and you configure the celery region in the airflow.cfg file, that I didn't have to set it anywhere else.

There's a bigger question of consistency between the various places where the region is set, but that's a separate question.

**Comment by villasv** [comment]
Alright. Made the comment on the README. I'll leave the issue open for a while, I haven't made up my mind if I should intervene on this or not.

**Comment by villasv** [comment]
After some thought, I decided to close it as a documentation problem. I understand that there might be an expectation to have the default aws connection pointing at the stack's region already, but those default connections are a deep from a database seed.

All we should do as infrastructure providers is to give Airflow environment variables. It's ultimately on their side to allow the environment to override behaviors or not. I guess we could make a PR that changes the AwsHook to prefer settings from the environment, but it's out of scope for this issue.
