### ISSUE TITLE
Trust celery to install thread safe version of billiard

### ISSUE THREAD

**Issue by villasv** [villasv/turbine#85]
`billiard==3.5.0.5` (as of today the default install from `celery[sqs]`) makes Celery fail to execute a proper warm shutdown.

Installing `billiard==3.5.0.4` fixed the issue.

**Comment by villasv** [comment]
Waiting for https://github.com/celery/billiard/issues/260 to be fixed, and hopefully Airflow will pick up the patch automatically

**Comment by villasv** [comment]
The fix will be picked up by Airflow 1.10.4
https://issues.apache.org/jira/browse/AIRFLOW-4299
https://github.com/apache/airflow/pull/5116

**Comment by meadowlark-bradsher** [comment]
How is this done manually in the meantime?

**Comment by villasv** [comment]
Closed in e573fda
