### ISSUE TITLE
there are no logs on the servers also do we need to modify anything in airlfow.cfg on any of the EC2s?

### ISSUE THREAD

**Issue by DevOpsAirflow** [villasv/turbine#90]
there are no logs on the servers also do we need to modify anything in airlfow.cfg on any of the EC2s?

**Comment by villasv** [comment]
Hi @DevOpsAirflow,

> there are no logs on the servers

Which logs, exactly? Task logs reside only on the worker instance that executed them (and are then sent to the logs S3 bucket). Airflow service logs are available through `systemd`'s [`journalctl`](https://www.freedesktop.org/software/systemd/man/journalctl.html). You can check the service logs with
```
sudo journalctl -u airflow | tail -n 50
```

If you're on the scheduler machine, you'll see the scheduler logs; in the webserver machine, the webserver logs; in a worker machine, the worker logs.

> do we need to modify anything in airlfow.cfg on any of the EC2s?

You don't *need* to modify the `airflow.cfg`, though you can do so if you want to.

**Comment by DevOpsAirflow** [comment]
Thanks for the quick reply. Do we need to do anything on RDS? When I run
airflow commands it’s giving error saying table does not exists. Airflow
list_dags like this.  I am trying to run your sample dag and it’s stuck.
Thanks

**Comment by villasv** [comment]
If you SSH into an EC2 instance, you need to load the Airflow service environment variables before manually running commands in the CLI. For convenience, there's a temp file with all variables that you can source:

```
$ source /tmp/env.sh
$ airflow list_dags
```

But you don't need to do anything on RDS to get started. If you deploy the stack, deploy the example DAG and Unpause it on the Airflow UI, it should start scheduling tasks in a few minutes. If you let the default of 0 worker machines in the AutoScaling group, it'll take about 5~10 minutes for the first worker to spin up.

If you to speed up testing, configure the stack to always have at least 1 worker machine up.

**Comment by DevOpsAirflow** [comment]
Thanks. Also I see in ASG of worker node. SQS is not picking.  It’s
defaultimg to SQS://Localhost/.  Do I need to set anything. Appreciate tour
help I am trying to setup your setup in our company for 3 weeks and tried
all options. Thanks

**Comment by villasv** [comment]
Are you getting some kind of error? The worker instances are not picking up tasks from the queue? Or are you trying to run some command from the CLI?

**Comment by DevOpsAirflow** [comment]
Hi Victor,

This is what I did
1) deployed cft with worker isntance minumum 1 - so total 3 servers are up
2) I am able to login to these boxes
3) EFS and all Meta configuration is deployed
4) Started servers like "sudo service airflow start"
5) I see all servers are up
6) i am able to access GUI
7) When I try to run sample dags from gui its not  working
8) i tried running sample.dag  using "airflow run sample dummy
2019-02-25T00:00:00 --local" . this ran and i see the log in S3 so looks
like if i do source /tmp/env,sh and run dag from cli its working.

I also see this SQS error on worker node not sure whether i need to include
/tmp/env.sh some where before running the server

Feb 27 04:28:47 ip-10-123-1-222.ec2.internal turbine[23743]: Trying again
in 32.00 seconds...
Feb 27 04:29:19 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:29:19,262: INFO/MainProcess] Starting new HTTP connection (1):
169.254.169.254
Feb 27 04:29:19 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:29:19,264: INFO/MainProcess] Starting new HTTP connection (1):
169.254.169.254
Feb 27 04:29:19 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:29:19,277: INFO/MainProcess] Starting new HTTPS connection (1):
queue.amazonaws.com
Feb 27 04:30:19 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:30:19,765: INFO/MainProcess] Starting new HTTPS connection (2):
queue.amazonaws.com
Feb 27 04:31:20 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:31:20,753: INFO/MainProcess] Starting new HTTPS connection (3):
queue.amazonaws.com
Feb 27 04:32:23 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:32:23,759: INFO/MainProcess] Starting new HTTPS connection (4):
queue.amazonaws.com
Feb 27 04:33:29 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:33:29,109: INFO/MainProcess] Starting new HTTPS connection (5):
queue.amazonaws.com
Feb 27 04:34:29 ip-10-123-1-222.ec2.internal turbine[23743]: [2019-02-27
04:34:29,155: *ERROR/MainProcess] consumer: Cannot connect to
sqs://localhost//: HTTPSConnectionPool(host='queue.amazonaws.com
<http://queue.amazonaws.com>', port=443): Max retries exceeded with url: /
(Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection
object at 0x7f57b9cb1860>, 'Connection to queue.amazonaws.com
<http://queue.amazonaws.com> timed out. (connect timeout=60)')).*
Feb 27 04:34:29 ip-10-123-1-222.ec2.internal turbine[23743]: Trying again
in 32.00 seconds...


*Questions*
1) What is the command to start servers
2) /mnt/efs .. what goes here.. all dags ? if yes then do i need to update
airflow.cfg to pick up the dags form this location instead of /airflow/dags
3) how to redirect webserver.log , scheduler.log and worker.log files to
/airflow folder
4) I do not see /airflow/dags folder.. do i need to create this manually?
5) Do you have any debugging or verifying steps
6) do u have any sample dags and steps to run

Appreciate your help

Thanks
Partha

**Comment by DevOpsAirflow** [comment]
BTW one more thing. I removed IGW and deploying in existing VPC becuase of
our company limitation. Here is my update template

SG and role are good .. SG i gave all traffic from 0.0.0.0/0 and role i
gave administrator access

**Comment by villasv** [comment]
> 4) Started servers like "sudo service airflow start"

You don't have to do that, services should be running after the EC2 machine initializes.

> 7) When I try to run sample dags from gui its not working

What do you mean "it's not working"? Are tasks not getting scheduled if you manually trigger the sample dag from the UI?

> 8) i tried running sample.dag using "airflow run sample dummy 2019-02-25T00:00:00 --local" . this ran and i see the log in S3 so looks like if i do source /tmp/env,sh and run dag from cli its working.

OK, this is a good sign. It seems everything is fine with the cluster, then.

> 1) What is the command to start servers

The command to start services is `sudo systemctl start airflow`, but you don't have to do that. Services will start automatically after the EC2 machine finishes its initialization.

> 2) /mnt/efs .. what goes here.. all dags ? if yes then do i need to update airflow.cfg to pick up the dags form this location instead of /airflow/dags

Whatever you want. You don't need to put anything in there.

> 3) how to redirect webserver.log , scheduler.log and worker.log files to /airflow folder

Why do you want to do that? Is `journalctl` not enough?

> 4) I do not see /airflow/dags folder.. do i need to create this manually?

If you don't want to change your DAGs directory, then you'll have to deploy your DAGs into that directory after it's created, yes.

> 5) Do you have any debugging or verifying steps

Not sure what you mean. To make sure everything is working, I deploy my example DAG and let it run for a while, see if everything is green.

> 6) do u have any sample dags and steps to run

Yes, it's already on the repository in the `src` directory.

**Comment by DevOpsAirflow** [comment]
For Question 4) Its not started i need to start it manually
5) Dags are in Queue and running state. Do you have think issue with sQS.
my assumption is scheduler put messages in SQS and workers instances will
consume those.

I am getting this error in worker server .. do i need to set anything for
sqs ?

Feb 28 02:55:28 ip-10-123-1-89.ec2.internal turbine[19009]: [2019-02-28
02:55:28,722: ERROR/MainProcess] consumer: *Cannot connect to
sqs://localhost//: H*TTPSConnectionPool(host='queue.amazonaws.com',
port=443): Max retries exceeded with url: / (Caused by
ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at
0x7f2edf01b4a8>, 'Connection to queue.amazonaws.com timed out. (connect
timeout=60)')).

**Comment by DevOpsAirflow** [comment]
I am also seeing this error in scheduler .. *{sqlalchemy.py:79} WARNING -
DB connection invalidated. Reconnecting...*

**Comment by villasv** [comment]
If services didn't start automatically, then some configuration of yours is preventing the EC2 initialization phase to complete successfully. Please provide the complete contents of the following initialization logfiles so I can take a closer look. (The second one might be too big to post here).

```
/var/log/cfn-init.log
/var/log/cfn-init-cmd.log
```

> do i need to set anything for sqs ?

Nope, the stack works as expected without further configuration. 
If there are connectivity problems between workers and SQS or RDS, it's probably because of you custom networking configurations.

**Comment by DevOpsAirflow** [comment]
Hi Victor,

I do not see any exceptions or errors in cloud-int.log .. I made one change
in cfn-signal in the first line \ was missing.. without that i was getting
exception so i added.

/opt/aws/bin/cfn-signal -e $? \
--region ${AWS::Region} \
--stack ${AWS::StackName} \
--resource AirflowScheduler

These below highlighted red are these errors or can i ignore these
warnings? Looks like based on below two warning it is not connecting to SQS
and RDS

Feb 28 02:55:28 ip-10-123-1-89.ec2.internal turbine[19009]: [2019-02-28
02:55:28,722: ERROR/MainProcess] consumer: *Cannot connect to
sqs://localhost//: H*TTPSConnectionPool(host='queue.amazonaws.com',
port=443): Max retries exceeded with url: / (Caused by
ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at
0x7f2edf01b4a8>, 'Connection to queue.amazonaws.com timed out. (connect
timeout=60)')).

 am also seeing this error in scheduler .. *{sqlalchemy.py:79} WARNING - DB
connection invalidated. Reconnecting...*

I will send these two log files and send it to you soon

Thanks
Partha

**Comment by villasv** [comment]
> I made one change in cfn-signal in the first line \ was missing.. without that i was getting exception so i added.

Nice catch! I'll create another issue to track this bug.

> These below highlighted red are these errors or can i ignore these warnings?

Those are errors indeed. But the first problem you should be focusing on diagnosing is why didn't your services start automatically. Everything else might be related.

I'll close this issue as it's totally diverted from the original question. Please do open new issues, but more specific ones.
